### PR TITLE
svg2png as peerDependencies

### PR DESCRIPTION
**Pull request by bung87**

### CODE REVIEW

**Comment by akabekobeko** [comment]
@bung87
Please explain the motive for this PR.

As v2.x, it depends on svg2png and has been verified with the final version 4.1.1. Therefore, it is treated as an implicitly installed dependencies.

**Comment by akabekobeko** [comment]
Supplement:

- Development of svg2png has stopped
- The bundle size of svg2png is large
- I want to use the user environment or any version of Chromium to guarantee idempotency

For that reason, icon-gen v3 will move to [@ akabeko / svg2png --npm] (https://www.npmjs.com/package/@akabeko/svg2png).

**Comment by bung87** [comment]
this is related to https://github.com/akabekobeko/npm-icon-gen/issues/121 before that fixed, I suggest make a minor change let svg2png as peerDependencies, so developers install it by themselves, the common format of icon is `png` as input, even developers get `svg` from designer they can export as png themselves, I personally dont like download extra large file.

**Comment by akabekobeko** [comment]
From now on, I removed `develop` to change the branch to` master` only. Therefore, this pull request was also closed in conjunction. 

I am considering switching to the `sharp` proposed in #135.

**Pull request closed without merging**
