### PR TITLE
change to sharp

### PR DESCRIPTION
**Pull request by mifi**
See #135

### CODE REVIEW

**Comment by mifi** [comment]
I tested it on my icons for https://github.com/mifi/lossless-cut and the icons look roughly the same (not pixel exact but very similar)

**Comment by akabekobeko** [comment]
Thank you! Check it out this weekend.

**Comment by akabekobeko** [comment]
@mifi 
I have confirmed that `sharp` can generate PNG from SVG. However, when I tried with `examples/` on this project, the top and bottom seem to be cut. 

```
$ npm pack
$ mv icon-gen-2.1.0.tgz examples/
$ cd examples
$ npm un icon-gen
$ npm i icon-gen-2.1.0.tgz
$ npm run ts:svg
```

Are there any settings to avoid this problem?

**svg2png**



**sharp**

favicon-228

**Comment by mifi** [comment]
I updated the code now, so it should now generate those correctly

here's how i ran it:

```bash
npm run watch
cd dist/bin
node . -i ../../examples/data/sample.svg -o ../../examples/data/ --icns --favicon
```

**Comment by mifi** [comment]
I also confirm it still works with my project https://github.com/mifi/lossless-cut after these changes (generates the same icons)

**Comment by akabekobeko** [comment]
@mifi 
I also confirmed that the whole image was rendered with the new commit in my environment, so I merged it. thank you!

**Comment by mifi** [comment]
great! thanks for making this module btw. all these different icon standards is a jungle so it's nice to have one package to generate all of them from svg.

**Pull request merged**
